#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.4f1_1d952368ca3a"
#define UNITY_VERSION_FULL_NICE "2018.3.4f1 (1d952368ca3a)"
#define UNITY_VERSION_BLD 1938723
#define UNITY_VERSION_DATE 1548841739
#define UNITY_VERSION_WIN "2018.3.4.1938723"
#define UNITY_VERSION_BRANCH "2018.3/staging"
